#!/bin/sh
cd /boot/home/projects/ports/setpermissions
package create -b setpermissions_0.1-2_gcc2.hpkg
sleep 0.5
package add setpermissions_0.1-2_gcc2.hpkg data documentation apps bin
sleep 0.5
addattr BeShare:Info "File permission manipulation utility" setpermissions_0.1-2_gcc2.hpkg
becopy setpermissions_0.1-2_gcc2.hpkg "/Storage/Haiku/My ports"
mv setpermissions_0.1-2_gcc2.hpkg /boot/home/projects/repo

sync